### ISSUE TITLE
EXILED 2.0.0 CurrentRoom.Zone

### ISSUE THREAD

**Issue by JasKill** [galaxy119/EXILED#122]
Seems to incorrectly determine the current zone of the player’s room
![Annotation 2020-06-08 190007](https://user-images.githubusercontent.com/57372449/84028943-cf4b0480-a9bb-11ea-8ab5-2c7498fa60a9.png)

And yes, about the Player.Died event, it defines ev.Target.Team is rip, not team when he died.

**Comment by iopietro** [comment]
Fixed in #124
