### ISSUE TITLE
Banned from discord?

### ISSUE THREAD

**Issue by arockstar28** [galaxy119/EXILED#126]
No idea why I was banned from the discord but I was. Maybe I got mad at someone who said I had a small brain?

**Comment by FruitBoi** [comment]
Yeah, we don’t ban people for no reason my dude.

**Comment by galaxy119** [comment]
You were banned for repeatedly asking for support in the wrong channel, regardless of being repeatedly told (by multiple people) that you were in the wrong channel, after which you simply told them to "fuck off".

**Comment by FruitBoi** [comment]
also known as "being a cunt"
