### ISSUE TITLE
Ban followup

### ISSUE THREAD

**Issue by arockstar28** [galaxy119/EXILED#127]
I know that I got mad and said “fuck off”, but these contributors who didn’t actually tell me where to post the issue were just reacting to my messages with :shrinkingbrain: which kind of made me mad because I still had no idea where to go for support. I assumed it was a bug report because I wasn’t able to launch the game. Only then was I told to go to plugin support but I didn’t think I would get support there (since it’s for plugins). I’m honestly sorry I would rather just move past this because I wanna keep using exiled and its plugins.

**Comment by arockstar28** [comment]
Can I atleast appeal somewhere?

**Comment by galaxy119** [comment]
You were told, several times, to go to the #support channel. The emotes were in response to your continued posting in the wrong channel after having been told where the proper place was.

**Comment by arockstar28** [comment]
I didn't see that until the 2nd or third message before my enraged statement.  Is there somewhere I can atleast appeal at?

**Comment by galaxy119** [comment]
It's been removed. Please keep posts to the appropriate channels in the future, thanks.
