### ISSUE TITLE
Please rename "Exiled Permissions" to just "Permissions" in .config\EXILED\Plugins

### ISSUE THREAD

**Issue by PatPeter** [galaxy119/EXILED#147]
Sorry for the premature creation of the issue and issue name spam, spilled rum on my keyboard and since then the keys have been sticking. Tried to clean it with Denatured Alcohol but it looks like the \ and Enter button are still getting stuck together.

Anyway, thank you so much for putting the Plugins folder inside the EXILED folder. This makes a lot more sense in terms of directory structure, more neat and orderly.

While you're changing the directory structure, could you please rename the "Exiled Permissions" folder to just "Permissions", or will the "permissions.yml" file be moved to the new EXILED\Configs folder?

Having a space in a directory can be a bitch on Linux, as I found out to my chagrin for a file in [on Smod2](https://github.com/ServerMod/Smod2/issues/74).

**Comment by galaxy119** [comment]
There *is* a config option for Exiled.Permissions to change the folder path, however the default path for the permissions file is being changed to .config/EXILED/Configs/permissions.yml

**Comment by PatPeter** [comment]
Thank you!
