### ISSUE TITLE
CurrentRoom.Zone and Round.ElapsedTime

### ISSUE THREAD

**Issue by JasKill** [galaxy119/EXILED#155]
Exiled 2.0.1
#124 Not fixed **CurrentRoom.Zone**, It defines zone as surface.
![zone](https://user-images.githubusercontent.com/57372449/87672921-e55b9a00-c79d-11ea-8ee3-d7e56ea0ec65.png)
**Round.ElapsedTime** why does it give 00:00:00, but if you write rtime then everything is fine.
![rtime](https://user-images.githubusercontent.com/57372449/87673104-2d7abc80-c79e-11ea-91e7-f93ec5fbd9e7.png)
Also Config does not generate static variables
![staticcfg](https://user-images.githubusercontent.com/57372449/87673685-1dafa800-c79f-11ea-907c-d06b1cdf0222.png)

**Comment by iRebbok** [comment]
Config should never use static variables/properties. As we're using YamlDotNet to serialize and deserialize the config.
This isn't a problem.

**Comment by iRebbok** [comment]
Correct display of the zone has been fixed: ![](https://i.imgur.com/5AwIPwo.png)

Someone missed the fact that enum had a default value of 0 and 0 was Surface lol
I haven't tested `Round.ElapsedTime`, so @JasKill could you test it from [***this***](https://github.com/galaxy119/EXILED/suites/925392624/artifacts/11336036) build?

**Comment by JasKill** [comment]
Yes I checked Round.ElapsedTime now it works like CurrentRoom.Zone. Thank.
