### ISSUE TITLE
Player.ChangingRole event and EscapingEventArgs

### ISSUE THREAD

**Issue by JasKill** [galaxy119/EXILED#161]
Called 2 times per player at the start of the round.
![cr](https://user-images.githubusercontent.com/57372449/87846841-2ae2a900-c8fd-11ea-8429-dd258ac5b5cc.png)
EscapingEventArgs IsAllowed switching to false does not work, it changes role in any case.

**Comment by iRebbok** [comment]
This happens because of the SmartClassPicker, it assigns the class to the player after.

**Comment by JasKill** [comment]
Okay, I turned off smart_class_picker and everything is fine now. The second problem should be solved #162.

**Comment by galaxy119** [comment]
Fixed with #162
