### ISSUE TITLE
Logging to {Server.Port}-RemoteAdminLog.txt incomplete

### ISSUE THREAD

**Issue by Kuponutmog** [galaxy119/EXILED#193]
Doesn't log anything past the initial command, so you don't know who's been jailed, who commands were run against, what was said with bc/pbc/abc etc.
![logs](https://user-images.githubusercontent.com/37111550/89134698-f38c1300-d51e-11ea-8685-66e51f658d8c.png)

**Comment by galaxy119** [comment]
This bug is already known, and will be addressed in a future update.

**Comment by iopietro** [comment]
Fixed in c5a86fc.
