### ISSUE TITLE
Without "exiled" everything started fine.

### ISSUE THREAD

**Issue by Tamago4a** [galaxy119/EXILED#196]
![121241241242414214124](https://user-images.githubusercontent.com/47304666/89266332-75bf2900-d63e-11ea-9197-0fc87f837391.png)

https://discordapp.com/channels/330432627649544202/472406493229219860/740109121994489869

**Comment by galaxy119** [comment]
Can't replicate.

**Comment by Tamago4a** [comment]
I still did not understand what was the matter, but when I downloaded the files 5 times and replaced everything, everything worked for me. What it is, I still do not understand. I am sorry that I wasted your time on this report.
