### ISSUE TITLE
Replace "Assembly-CSharp.dll" infinite restart。

### ISSUE THREAD

**Issue by RJCooLEST** [galaxy119/EXILED#200]
![image](https://user-images.githubusercontent.com/56374469/89444169-e02db180-d783-11ea-9a40-a1ade49e54d1.png)

**Comment by galaxy119** [comment]
Did you validate game files via steam prior to installing exiled?

**Comment by RJCooLEST** [comment]
yep,When i try to replace “ Assembly-CSharp.dll”,and “MultiAdmin.exe”Doesn't seem to be working.

After this. in ”steamcmd“ ”app_update 786920“  to, Resume normal operation .

**Comment by RJCooLEST** [comment]
;)I think i found the problem Because i used the old 1.11.0 Releases version.
·····I don’t remember the last time I downloaded it and put it together.

This is my fault :( .Thank your help.

**Comment by RJCooLEST** [comment]
> ;）我认为我发现了问题，因为我使用了旧的1.11.0 Releases版本。
> ·····我不记得上次下载并将其放在一起的时候了。
> 
> 这是我的错:(。谢谢您的帮助。
