### ISSUE TITLE
[ERROR] [Exiled.Updater] #

### ISSUE THREAD

**Issue by RJCooLEST** [galaxy119/EXILED#228]
![image](https://user-images.githubusercontent.com/56374469/90539841-f2134980-e1b2-11ea-9b22-75cc659e42b9.png)

I once submitted this question to other plugins ....
Because this problem appears intermittently that affects my judgment.

Really appreciate your help
:)

**Comment by RJCooLEST** [comment]
Just to add, is it just my network reason?

**Comment by iRebbok** [comment]
Yea, the exception tells `Connection refused`
