### ISSUE TITLE
Something strange

### ISSUE THREAD

**Issue by Tamago4a** [galaxy119/EXILED#257]
At the same time, the same IP addresses are constantly duplicated in my console. I get this error quite often when the round is restarted.
![Безымянный](https://user-images.githubusercontent.com/47304666/94808188-691a3f80-03f9-11eb-88b6-512c86388f9d.png)
Sometimes this happens.
![Снимок](https://user-images.githubusercontent.com/47304666/94807944-032db800-03f9-11eb-91b4-145634ed72ee.PNG)
If the reason is not EXILED, then could you tell me where to look for the reason?

**Comment by iRebbok** [comment]
Currently I see that you've attached two screenshots which:
1. literally irrelevant to exiled because your server can't restart a round for a minute
2. is an excerpt from the console that doesn't provide any information about the possible cause, you should attach a round log for further analysis

**Comment by Tamago4a** [comment]
> Currently I see that you've attached two screenshots which:
> 
> 1. literally irrelevant to exiled because your server can't restart a round for a minute
> 2. is an excerpt from the console that doesn't provide any information about the possible cause, you should attach a round log for further analysis

What kind of logs are needed?

**Comment by iRebbok** [comment]
> What kind of logs are needed?

A console log and an unity log because that's weird

**Comment by Tamago4a** [comment]
> > What kind of logs are needed?
> 
> A console log and an unity log because that's weird

Where can I get both of these logs? In what path?

**Comment by iRebbok** [comment]
> Where can I get both of these logs? In what path?
Literally depends on a console, for MA those logs are located in a `logs` folder; LA doesn't have that feature

**I've to close the issue without logs.**

**Comment by Tamago4a** [comment]
> > Where can I get both of these logs? In what path?
> 
> Literally depends on a console, for MA those logs are located in a `logs` folder; LA doesn't have that feature
> 
> **I've to close the issue without logs.**

Okay. Close. I will install multiadmin. And if errors are repeated, I will provide all the necessary logs.
