### ISSUE TITLE
[BUG] Exiled.Loader download pre-release even if he shoundn't

### ISSUE THREAD

**Issue by adarkaz** [galaxy119/EXILED#2684]
**Describe the bug**
Exiled.Loader download pre-release even if he shoundn't. 
should_download_testing_releases - false

**To Reproduce**
1. Have should_download_testing_releases value = false
2. Restart server
3. Get the new update even it marked as pre-release (i get 9.0.0-alpha.10)
4. Restart server again, get updated to pre-release version
**Expected behavior**
New version not found, not updating

**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured
https://pastebin.com/EfTH0RCu - cutted LocalAdmin log
**EXILED Version ("latest" is not a version):**
8.9.6 

**Results of `pluginmanager show` command in console:**
https://pastebin.com/DZekGLfC (backup to old version)

**Comment by VALERA771** [comment]
Iirc someone (@Misfiy) accidentally forgot to put pre release tag, so alpha.10 was installed as a normal release
