### ISSUE TITLE
How can I determine which plugin is overflowing RAM? Can MA logs help with this?

### ISSUE THREAD

**Issue by Tamago4a** [galaxy119/EXILED#293]
![image](https://user-images.githubusercontent.com/47304666/98139166-ef341500-1ed4-11eb-8db8-17c8d098efdf.png)
![image](https://user-images.githubusercontent.com/47304666/98139634-78e3e280-1ed5-11eb-8f31-43c9f9b7ef60.png)

**Comment by PintTheDragon** [comment]
As far as I know, there is no built-in profiler for EXILED. You can check the logs and see if a plugin is causing a lot of errors, or try removing plugins one by one to try to find the one causing this issue.

**Comment by Tamago4a** [comment]
The reason was that some plugin worked through the ass. Then I discovered it by elimination. When I found him I decided to check if he was updated in his channel in your discord. It turned out that it could have been updated by that time and the problem would have been solved immediately.

**Comment by iRebbok** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plugin Performance Profiler](https://trello.com/c/QeSLP24M/36-plugin-performance-profiler)
