### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Fluffy41** [galaxy119/EXILED#313]
It wont let me connect over the IP (when i connect the % stays at 0)

**Comment by iRebbok** [comment]
Exiled can't prevent you from connecting a server, except that one plugin rejects your connection request.

To connect a local server use IP: `localhost:port` - replace `port` with your server's port, by default it's 7777.
To connect a hosted server use IP assigned by a hosting provider (ex. `216.189.157.205:7777`, port is also needed).
