### ISSUE TITLE
I have suggest.

### ISSUE THREAD

**Issue by Tamago4a** [galaxy119/EXILED#323]
I would like to suggest that all plugins have a general view of how the config should look. Just for the beauty of the config. I understand that many of these things work anyway, but it would remove a lot of unnecessary questions and just make the config cleaner and more beautiful.
More details here:
Cassie:
![image](https://user-images.githubusercontent.com/47304666/99987343-6583b300-2dc1-11eb-8d1b-261738bb29ab.png)
If cassie should be silent:
![image](https://user-images.githubusercontent.com/47304666/99987558-ada2d580-2dc1-11eb-856c-e95f67950640.png)
And this example is essentially the same not entirely correct. By sound logic, it should be like this:
![image](https://user-images.githubusercontent.com/47304666/99990864-67e80c00-2dc5-11eb-97c0-bd8499ef345a.png)

BroadCast
![image](https://user-images.githubusercontent.com/47304666/99988499-bcd65300-2dc2-11eb-9f58-d09838bb0646.png)
And this
![image](https://user-images.githubusercontent.com/47304666/99990605-12136400-2dc5-11eb-9a0a-903ec49078d6.png)

Other:
![image](https://user-images.githubusercontent.com/47304666/99988242-7680f400-2dc2-11eb-9423-0e08247359f0.png)

Lists:
![image](https://user-images.githubusercontent.com/47304666/99989786-155a2000-2dc4-11eb-80a3-28f04f813b24.png)

Perhaps for some it will seem nonsense. But why not just bring the whole config back to normal. It would be cool.

**Comment by KadeDev** [comment]
Heres a cool thing about open-source creative-commons. You can modify what ever you like, as long as you dont claim its yours. If you want a plugin to act like this (and yes you've used my plugin as an example here) you can. No one is stopping you. Just stop telling people to change something so personalized as their own plugin config.

**Comment by Tamago4a** [comment]
> Heres a cool thing about open-source creative-commons. You can modify what ever you like, as long as you dont claim its yours. If you want a plugin to act like this (and yes you've used my plugin as an example here) you can. No one is stopping you. Just stop telling people to change something so personalized as their own plugin config.

I'm talking about bringing everything to one form. I don't want to see another Smod in which everything is through the ass. I am asking for a completely adequate thing. This is done once during the "plug-in life" and is no longer touched.

And I'll add that not all of your plugins are listed in the example. And I will add that this list also contains my personal plugins that I would only redo if everyone came to a common opinion. All the same, these plugins work on Yaml syntax, so maybe we will stick to it?

**Comment by KadeDev** [comment]
> > Heres a cool thing about open-source creative-commons. You can modify what ever you like, as long as you dont claim its yours. If you want a plugin to act like this (and yes you've used my plugin as an example here) you can. No one is stopping you. Just stop telling people to change something so personalized as their own plugin config.
> 
> I'm talking about bringing everything to one form. I don't want to see another Smod in which everything is through the ass. I am asking for a completely adequate thing. This is done once during the "plug-in life" and is no longer touched.
> 
> And I'll add that not all of your plugins are listed in the example. And I will add that this list also contains my personal plugins that I would only redo if everyone came to a common opinion. All the same, these plugins work on Yaml syntax, so maybe we will stick to it?
> Damn it, I really don't understand what's the problem then? I'm just asking the config to look nice.

do it yourself then, forcing wont help you.

**Comment by Tamago4a** [comment]
> do it yourself then, forcing wont help you.

Where in this text am I forcing you to do this?

**Comment by RogerFK** [comment]
> Wait a minute. I think I got it. Do you want me to do this for you and give you the correct dll file?

That's not what he said. He just told you to change the Serializer if you didn't like it.

Anyways:
1. This isn't a scripting language, and variable types don't have to be guessed from their context. They're already defined in their respective plugin's config classes.
2. Coding with dynamic variables would be a mess.

Long explanation:

I'm thinking doing this would be a pain in the ass to do (even making an `exiled_serializer: MySerializer.dll` config would be a mess... the only way I'd see would be adding an optional `Serializer-XXXX.dll` file or a `serializer.txt` file *somewhere*). Either way, you would have to edit how EXILED's serializer works.

Here's the deal: this is a serializer with [statically and strongly typed variables](https://android.jlelse.eu/magic-lies-here-statically-typed-vs-dynamically-typed-languages-d151c7f95e2b). The type of the variables don't have to be guessed from their context, unlike Python, where you just do `myVar = 'Hello world!'`. In C#, types are immutable **unless** the coder specifically says a type is `dynamic` (in which case it depends on the serializer, **maybe** YamlDotNet does give you 'string' and stuff if you use dynamic on a serializable).

Using `dynamic` would overcomplicate code, it doesn't make any sense to do it, and the configs wouldn't really look cleaner. For example, when we want a `float` variable, these numbers wouldn't be `0.05` but `0.05f`. Added to the fact, for whatever reason, YamlDotNet apparently messes up our floats and adds a lot of decimals (`0.0500000001f` would look even messier.). One lines comparing a float against a float would turn into a type-checking headache.

anyways my final point: can't you really understand `0.5` is a number, and `Hello my fellow dbois` is a string? plus, you would break everyone else's configs...

**Comment by galaxy119** [comment]
This would be a breaking change in formatting the config serializer uses, for very little (in my opinion, none at all) gain other than 'some' people 'may' find it more 'aesthetically pleasing' to look at.

Re-writing the serializer to use this formatting would be a pain in the ass, for no reason, and would break everyone's config files instantly resetting them all back to default, if the server even loads them at all.

I'm going to say hard no on this one.

**Comment by Tamago4a** [comment]
Okay. Well, at least I got a normal answer.

**Comment by KadeDev** [comment]
> Okay. Well, at least I got a normal answer.
> Do I understand correctly that if I now put quotes everywhere in my configs, then everything will still work for me?

Try it, if it breaks. Modify it till it doesn't. You can control your own server, exiled is open source.
