### ISSUE TITLE
InteractingDoor patch does not account correctly for bypass mode.

### ISSUE THREAD

**Issue by o5zereth** [galaxy119/EXILED#348]
I tried to open a door with bypass while it was locked; It didn't work, which I knew wasn't how the base game handled bypass mode; I tried it in a single-player server without EXILED and bypass allowed opening of locked doors; I checked the source code for the event and indeed found that it wasn't handling the bypass mode correctly.

You can see the source code here under Exiled.Events.Patches.Events.Player.InteractingDoor.cs:
![codeimage](https://user-images.githubusercontent.com/70236765/101955892-a4d93e80-3bcc-11eb-8c2b-7529ca24f391.png)
The issue occurs because if (ev.IsAllowed && !ev.Door.locked) doesn't actually come up as true if the door is locked, so it doesn't open the door.

**Comment by Thundermaker300** [comment]
I can put in a PR to fix this when I get home, if someone doesn't beat me to it.

**Comment by o5zereth** [comment]
@Thundermaker300 no need to make a plugin, I could myself but I just wanted it fixed by exiled so there's no need to make a plugin

**Comment by Thundermaker300** [comment]
I wasn't going to make a plugin - I said I can put a PR to fix this when I get home.

**Comment by o5zereth** [comment]
@Thundermaker300 that's what i meant, no need to make a PR

**Comment by Thundermaker300** [comment]
@o5zereth but that's how exiled fixes it??

**Comment by Thundermaker300** [comment]
Update: I'm dumb, ignore me

**Comment by Thundermaker300** [comment]
Fixed in #349
