### ISSUE TITLE
After I've installed EXILED, the SCP SL Server will not start. 

### ISSUE THREAD

**Issue by SwiftKraft** [galaxy119/EXILED#380]
I have installed EXILED using the installer, and the server will not start for some reason. But when I replaced the modified `Assembly-CSharp.dll` with the original one, it works again.

**Comment by EsserGaming** [comment]
Thats because you did not install the pre-release of the exiled installer (done by using the batch file)

**Comment by SwiftKraft** [comment]
What do you mean by "the batch file"

**Comment by iRebbok** [comment]
The README file perfectly describes what you're looking for, please look at [it](https://github.com/galaxy119/EXILED#linux).
