### ISSUE TITLE
096 does not gain extra rage per target when targets are empty

### ISSUE THREAD

**Issue by Xypixian** [galaxy119/EXILED#383]
The vanilla game adds 3 seconds of rage time when you gain an additional target. The game checks for two conditions, either your target list being empty (second target gained during enrage), or if you are already enraged (in case all your targets die, you still get the extra time because you are already enraged). The code currently only has "!__instance._targets.IsEmpty", when it should be "!__instance._targets.IsEmpty || __instance.Enraged", according to what I asked Build.

**Comment by iRebbok** [comment]
Thank you for reposting this! I've fixed it in 342466d. New release will include the fix.
